namespace Develop
{
    [bindable]
    [default_interface]
    static runtimeclass AppSettings
    {
        static IVectorView<String> SupportedFileTypes { get; };
        static Windows.Foundation.IAsyncAction InitializeAsync();
        static DevelopManaged.SettingsViewModel Preferences { get; };
        static String GetLocalized(String key);
    }
}
