import "IAsyncClosable.idl";

namespace Develop
{
    [bindable]
    [default_interface]
    static runtimeclass AppSettings
    {
        static IVectorView<String> SupportedFileTypes { get; };
        static Windows.Foundation.IAsyncAction InitializeAsync();
        static Boolean DialogShown { get; set; };
        static void AddToCloseList(IAsyncClosable view);
        static void RemoveFromCloseList(IAsyncClosable view);
        static Boolean IsFileTypeSupported(String fileType);
    }
}
