namespace Develop
{
    [default_interface]
    runtimeclass CodeEditor : Windows.UI.Xaml.Controls.UserControl, Windows.UI.Xaml.Data.INotifyPropertyChanged, Shared.IAsyncClosable
    {
        CodeEditor(Windows.Storage.StorageFile file);
        Windows.Storage.StorageFile WorkingFile { get; };
        Boolean Saved;
    }
}