namespace Develop
{
    [default_interface]
    runtimeclass CodeEditor : Windows.UI.Xaml.Controls.UserControl, Windows.UI.Xaml.Data.INotifyPropertyChanged, JUVStudios.IAsyncClosable
    {
        CodeEditor(Windows.Storage.StorageFile file);
        Boolean Saved { get; set; };
        Boolean FileLoaded { get; set; };
        TextEditor.UI.SyntaxEditor TextView { get; };
    }
}