namespace Develop
{
    [default_interface]
    runtimeclass HomePage : Windows.UI.Xaml.Controls.UserControl
    {
        HomePage();
        String OpenTitleId { get; };
        void SetPageIndex(UInt32 index);
    }
}
