namespace Develop
{
	interface IAsyncClosable requires Windows.Foundation.IClosable
	{
		Boolean PrepareClose();
		Windows.Foundation.IAsyncAction CloseAsync();
	}

	interface ISuspendable requires IAsyncClosable
	{
		Windows.Foundation.IAsyncAction SuspendAsync();
		Windows.Foundation.IAsyncAction ResumeAsync();
	}
}