namespace Develop
{
    [bindable]
    [default_interface]
    runtimeclass SettingsViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        String FontFamily { get; set; };
        UInt32 FontSize { get; set; };
        Boolean AutoSave { get; set; };
        Boolean DisableSound { get; set; };
        static String AboutText { get; };
        static SettingsViewModel Instance { get; };
    }
}