namespace Develop
{
    [default_interface]
    runtimeclass SettingsView : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SettingsView();
        Int32 SelectedPage { get; set; };
    }
}

