import "ShellView.idl";
import "BindableBase.idl";

namespace Develop
{
    [bindable]
    [default_interface]
    runtimeclass ShellViewModel : BindableBase
    {
        ShellViewModel();
        IObservableVector<ShellView> Instances{ get; };
        ShellView SelectedInstance{ get; set; };
        void AddStorageItems(IVectorView<Windows.Storage.IStorageItem2> sItems);
    }
}
