import "ShellView.idl";

namespace Develop
{
    [bindable]
    [default_interface]
    runtimeclass ShellViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        ShellViewModel();
        IObservableVector<ShellView> Instances{ get; };
        ShellView SelectedInstance{ get; set; };
        void AddStorageItems(IVectorView<Windows.Storage.IStorageItem2> sItems);
    }
}

