namespace Develop
{
    [bindable]
    [default_interface]
    runtimeclass ShellViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        ShellViewModel();
        Windows.Foundation.Collections.IObservableVector<DevelopManaged.ShellView> Instances{ get; };
        DevelopManaged.ShellView SelectedInstance{ get; set; };
        void AddInstances(Windows.Foundation.Collections.IVectorView<DevelopManaged.ShellView> views);
    }
}
